version: '3'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - 4000:4000
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/jobportaldb

  frontend:
    build: ./frontend
    ports:
      - 3000:80
    depends_on:
      - backend

volumes:
  mongo-data:
