name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [backend, frontend]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies and build ${{ matrix.service }}
      working-directory: ${{ matrix.service }}
      run: |
        npm install
        npm run build

    - name: Run tests for ${{ matrix.service }}
      working-directory: ${{ matrix.service }}
      run: |
        npm test || echo "No tests found"
